{ config, pkgs, ... }:
{

  # Configurations are set in disko-config.nix!

  # mdadm.conf generated by `mdadm --detail --scan`
  # TODO
  boot.swraid.enable = true;
  boot.swraid.mdadmConf = ''
    MAILADDR root
  '';

  # TODO: RAID Monitoring
  # TODO: Set spin-down time of physical disks

  services.fwupd.daemonSettings.EspLocation = pkgs.lib.mkForce config.disko.devices.disk.system-1.content.partitions.boot.content.mountpoint;

  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint =
    config.disko.devices.disk.system-1.content.partitions.boot.content.mountpoint;

  qois.lanzaboote = {
    enable = true;
    extraEfiSysMountPoints = [
      config.disko.devices.disk.system-2.content.partitions.boot.content.mountpoint
    ];

    autoCryptenroll.devices = {
      system = config.boot.initrd.luks.devices.crypted_system.device;
      data = config.boot.initrd.luks.devices.crypted_data.device;
    };
  };
}
