# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.loader.grub.extraConfig = "\n    serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1\n    terminal_input serial\n    terminal_output serial\n  ";
  boot.initrd.availableKernelModules = [
    "ahci"
    "ohci_pci"
    "xhci_pci"
    "ahci"
    "ehci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
    "r8169"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "virtio"
    "tun"
  ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "console=ttyS0,115200n8" ];

  hardware.cpu.amd.updateMicrocode = true;

  nix.settings.max-jobs = lib.mkDefault 2;
}
