
" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
" Avoid side effects when it was already reset.
if &compatible
  set nocompatible
endif

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
" Revert with: ":delcommand DiffOrig".
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
          \ | wincmd p | diffthis
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"




""""""""""""""""""""""""""
"  Design Settings
""""""""""""""""""""""""""
set background=dark
colorscheme elflord

""""""""""""""""""""""""""
" Other Settings
""""""""""""""""""""""""""
set ignorecase                  " Ignore search case
set autoindent                  " Newline with automatic text indent
set ruler                       " Show current position
set pastetoggle=<F2>
set ignorecase
set hidden

set splitbelow
set splitright

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set listchars="eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:␣"
set grepprg=ack\ -k

filetype plugin indent on
syntax on

